language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

services:
  - redis-server
  - memcached

before_install:
  - gem update --system
  - gem install bundler

cache: bundler

script: bundle exec rake

notifications:
  email: false
