name: ❓ Question or Support Request
description: Questions and requests for support
title: "[Question/Support] <title>"
labels: [question, support, needs-triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Describe your question or ask for support
    description: A concise description of what you would like support with
  validations:
    required: true
