name: Release
on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]
  workflow_dispatch: # allow manual deployment through GitHub Action UI
jobs:
  version-check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    outputs:
      changed: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if version has been updated
        id: check
        uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0
        with:
          files: lib/procore/version.rb
  release:
    runs-on: ubuntu-latest
    needs: version-check
    if: ${{ github.event_name == 'workflow_dispatch' || needs.version-check.outputs.changed == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Installing dependencies
        run: bundle install
      - name: Build gem file
        run: bundle exec rake build
      - uses: fac/ruby-gem-setup-credentials-action@v2
        with:
          user: ""
          key: rubygems
          token: ${{secrets.RUBY_GEMS_API_KEY}}
      - uses: fac/ruby-gem-push-action@v2
        with:
          key: rubygems
