name: Test
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.0', '3.1', '3.2']
        include:
          - os: ubuntu-20.04
            ruby: '2.7'
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis:6.2.6
        ports:
          - 6379:6379
      memcached:
        image: memcached:1.6.18
        ports:
          - 11211:11211
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Installing dependencies
        run: bundle install
      - name: Run tests
        run: COVERAGE=true bundle exec rake
